left_wheel_encoder_topic: ras_group8_left/motorcontrol/encoder
right_wheel_encoder_topic: ras_group8_right/motorcontrol/encoder
publish_topic: odom
header_frame_id: odometry
child_frame_id: robot

encoder_ticks_per_rev: 900
wheel_circumference: 0.22934
wheel_distance: 0.24
wheel_radius: 0.0365

